---
- name: update apt-get
  apt: update_cache=yes cache_valid_time=3600

- name: install packages
  apt:
    name={{ item }}
    state=present
  with_items:
    - locales
    - ncurses-term
    - mc
    - ranger
    - zsh
    - htop
    - less
    - file
    - psmisc
    - iftop
    - nload
    - lsof
    - tmux
    - vim

- name: ensure user
  user:
    name={{ console.user }}
    shell=/bin/zsh
    groups=sudo,devops
    append=yes

# - name: change motd
# - name: install packages config
# - set locales to 'en_US.UTF-8'
