---
- name: update apt-get
  apt: update_cache=yes cache_valid_time=3600

- name: install packages
  apt:
    name={{ item }}
    state=present
  with_items: "{{ console.tools }}"

- name: install packages
  apt:
    name={{ item }}
    state=present
  with_items: "{{ console.utils }}"

- include: user.yml
- include: zsh.yml
