---
- name: Set as default shell
  user: name={{ console.user }} shell=/bin/zsh

- name: ensure ~/history
  file: path=~{{ console.user }}/history state=directory mode=0700

- name: Generate ~/.zshrc
  template:
    mode=0644
    src=zshrc.j2
    owner={{ console.user }}
    dest=~{{ console.user }}/.zshrc
